default: &default
  adapter: postgresql
  pool: 15
  timeout: 5000

test:
  <<: *default
  adapter: sqlite3
  database: db/greetings_test.sqllite3

development:
  <<: *default
  database:   <%= ENV['GREETINGS_DB_NAME']     || 'greetings_development' %>
  host:       <%= ENV['GREETINGS_DB_HOST']     || ENV['DOCKER_HOST'].nil? ? 'localhost': ENV['DOCKER_HOST'][/\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\b/] %>
  port:       <%= ENV['GREETINGS_DB_PORT']     || '5433'         %>
  username:   <%= ENV['GREETINGS_DB_USERNAME'] || 'greetings'    %>
  password:   <%= ENV['GREETINGS_DB_PASSWORD'] || ''             %>